/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tac ;

import Tac.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class TacGUIImplementation extends javax.swing.JFrame implements TacAgentGUI {
    private TacAgent myAgent;
    /**
     * Creates new form TicGUIImplementation
     */
    
    Map<Integer, JButton> mapLLToButton = new HashMap<>();
    
    
    public TacGUIImplementation() {
        initComponents();
 
        JPanel[] rows = {
            row1,
            row2,
            row3,
            row4,
            row5,
            row6,
            row7,
            row8,
            };
        
        ActionListener btnListener = new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent evt){
              JButton clickedButton = (JButton) evt.getSource();
              BtnActionPerformed(clickedButton);
          }
        };
        
        int i = 0;

        for (JPanel row : rows) {
    
            int j = 0;
            row.setName("row" + (i+1)); // Set row names too if you want
            
            for (Component col : row.getComponents()) {
                JButton btn = (JButton) col;
                btn.setName("Btn"+(i*8+j));
                btn.addActionListener(btnListener);
                mapLLToButton.put((i*8+j), btn);
//                System.out.println("Tac: "+(i*8+j) + " "+ i +" "+j +" "+ btn.getName());

                j++;
            }
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matrix = new javax.swing.JPanel();
        row1 = new javax.swing.JPanel();
        Btn11 = new javax.swing.JButton();
        Btn12 = new javax.swing.JButton();
        Btn13 = new javax.swing.JButton();
        Btn14 = new javax.swing.JButton();
        Btn15 = new javax.swing.JButton();
        Btn16 = new javax.swing.JButton();
        Btn17 = new javax.swing.JButton();
        Btn18 = new javax.swing.JButton();
        row2 = new javax.swing.JPanel();
        Btn19 = new javax.swing.JButton();
        Btn20 = new javax.swing.JButton();
        Btn21 = new javax.swing.JButton();
        Btn22 = new javax.swing.JButton();
        Btn23 = new javax.swing.JButton();
        Btn24 = new javax.swing.JButton();
        Btn25 = new javax.swing.JButton();
        Btn26 = new javax.swing.JButton();
        row3 = new javax.swing.JPanel();
        Btn35 = new javax.swing.JButton();
        Btn36 = new javax.swing.JButton();
        Btn37 = new javax.swing.JButton();
        Btn38 = new javax.swing.JButton();
        Btn39 = new javax.swing.JButton();
        Btn40 = new javax.swing.JButton();
        Btn41 = new javax.swing.JButton();
        Btn42 = new javax.swing.JButton();
        row4 = new javax.swing.JPanel();
        Btn27 = new javax.swing.JButton();
        Btn28 = new javax.swing.JButton();
        Btn29 = new javax.swing.JButton();
        Btn30 = new javax.swing.JButton();
        Btn31 = new javax.swing.JButton();
        Btn32 = new javax.swing.JButton();
        Btn33 = new javax.swing.JButton();
        Btn34 = new javax.swing.JButton();
        row5 = new javax.swing.JPanel();
        Btn43 = new javax.swing.JButton();
        Btn44 = new javax.swing.JButton();
        Btn45 = new javax.swing.JButton();
        Btn46 = new javax.swing.JButton();
        Btn47 = new javax.swing.JButton();
        Btn48 = new javax.swing.JButton();
        Btn49 = new javax.swing.JButton();
        Btn50 = new javax.swing.JButton();
        row6 = new javax.swing.JPanel();
        Btn51 = new javax.swing.JButton();
        Btn52 = new javax.swing.JButton();
        Btn53 = new javax.swing.JButton();
        Btn54 = new javax.swing.JButton();
        Btn55 = new javax.swing.JButton();
        Btn56 = new javax.swing.JButton();
        Btn57 = new javax.swing.JButton();
        Btn58 = new javax.swing.JButton();
        row7 = new javax.swing.JPanel();
        Btn67 = new javax.swing.JButton();
        Btn68 = new javax.swing.JButton();
        Btn69 = new javax.swing.JButton();
        Btn70 = new javax.swing.JButton();
        Btn71 = new javax.swing.JButton();
        Btn72 = new javax.swing.JButton();
        Btn73 = new javax.swing.JButton();
        Btn74 = new javax.swing.JButton();
        row8 = new javax.swing.JPanel();
        Btn59 = new javax.swing.JButton();
        Btn60 = new javax.swing.JButton();
        Btn61 = new javax.swing.JButton();
        Btn62 = new javax.swing.JButton();
        Btn63 = new javax.swing.JButton();
        Btn64 = new javax.swing.JButton();
        Btn65 = new javax.swing.JButton();
        Btn66 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        row1.setName("row1"); // NOI18N

        Btn11.setEnabled(false);
        Btn11.setName("Btn11"); // NOI18N
        Btn11.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn11ActionPerformed(evt);
            }
        });

        Btn12.setEnabled(false);
        Btn12.setName("Btn12"); // NOI18N
        Btn12.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn12ActionPerformed(evt);
            }
        });

        Btn13.setEnabled(false);
        Btn13.setName("Btn13"); // NOI18N
        Btn13.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn13ActionPerformed(evt);
            }
        });

        Btn14.setEnabled(false);
        Btn14.setName("Btn11"); // NOI18N
        Btn14.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn14ActionPerformed(evt);
            }
        });

        Btn15.setEnabled(false);
        Btn15.setName("Btn12"); // NOI18N
        Btn15.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn15ActionPerformed(evt);
            }
        });

        Btn16.setEnabled(false);
        Btn16.setName("Btn13"); // NOI18N
        Btn16.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn16ActionPerformed(evt);
            }
        });

        Btn17.setEnabled(false);
        Btn17.setName("Btn12"); // NOI18N
        Btn17.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn17ActionPerformed(evt);
            }
        });

        Btn18.setEnabled(false);
        Btn18.setName("Btn11"); // NOI18N
        Btn18.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row1Layout = new javax.swing.GroupLayout(row1);
        row1.setLayout(row1Layout);
        row1Layout.setHorizontalGroup(
            row1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row1Layout.setVerticalGroup(
            row1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row1Layout.createSequentialGroup()
                .addGroup(row1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        Btn11.getAccessibleContext().setAccessibleName("Btn11");
        Btn12.getAccessibleContext().setAccessibleName("Btn12");
        Btn13.getAccessibleContext().setAccessibleName("Btn13");

        row2.setName("row2"); // NOI18N

        Btn19.setEnabled(false);
        Btn19.setName("Btn11"); // NOI18N
        Btn19.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn19ActionPerformed(evt);
            }
        });

        Btn20.setEnabled(false);
        Btn20.setName("Btn12"); // NOI18N
        Btn20.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn20ActionPerformed(evt);
            }
        });

        Btn21.setEnabled(false);
        Btn21.setName("Btn13"); // NOI18N
        Btn21.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn21ActionPerformed(evt);
            }
        });

        Btn22.setEnabled(false);
        Btn22.setName("Btn11"); // NOI18N
        Btn22.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn22ActionPerformed(evt);
            }
        });

        Btn23.setEnabled(false);
        Btn23.setName("Btn12"); // NOI18N
        Btn23.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn23ActionPerformed(evt);
            }
        });

        Btn24.setEnabled(false);
        Btn24.setName("Btn13"); // NOI18N
        Btn24.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn24ActionPerformed(evt);
            }
        });

        Btn25.setEnabled(false);
        Btn25.setName("Btn11"); // NOI18N
        Btn25.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn25ActionPerformed(evt);
            }
        });

        Btn26.setEnabled(false);
        Btn26.setName("Btn12"); // NOI18N
        Btn26.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row2Layout = new javax.swing.GroupLayout(row2);
        row2.setLayout(row2Layout);
        row2Layout.setHorizontalGroup(
            row2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row2Layout.setVerticalGroup(
            row2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row2Layout.createSequentialGroup()
                .addGroup(row2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        row3.setName("row3"); // NOI18N

        Btn35.setEnabled(false);
        Btn35.setName("Btn11"); // NOI18N
        Btn35.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn35ActionPerformed(evt);
            }
        });

        Btn36.setEnabled(false);
        Btn36.setName("Btn12"); // NOI18N
        Btn36.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn36ActionPerformed(evt);
            }
        });

        Btn37.setEnabled(false);
        Btn37.setName("Btn13"); // NOI18N
        Btn37.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn37ActionPerformed(evt);
            }
        });

        Btn38.setEnabled(false);
        Btn38.setName("Btn11"); // NOI18N
        Btn38.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn38ActionPerformed(evt);
            }
        });

        Btn39.setEnabled(false);
        Btn39.setName("Btn12"); // NOI18N
        Btn39.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn39ActionPerformed(evt);
            }
        });

        Btn40.setEnabled(false);
        Btn40.setName("Btn13"); // NOI18N
        Btn40.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn40ActionPerformed(evt);
            }
        });

        Btn41.setEnabled(false);
        Btn41.setName("Btn12"); // NOI18N
        Btn41.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn41ActionPerformed(evt);
            }
        });

        Btn42.setEnabled(false);
        Btn42.setName("Btn11"); // NOI18N
        Btn42.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn42ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row3Layout = new javax.swing.GroupLayout(row3);
        row3.setLayout(row3Layout);
        row3Layout.setHorizontalGroup(
            row3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Btn35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row3Layout.setVerticalGroup(
            row3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row3Layout.createSequentialGroup()
                .addGroup(row3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        row4.setName("row4"); // NOI18N

        Btn27.setEnabled(false);
        Btn27.setName("Btn11"); // NOI18N
        Btn27.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn27ActionPerformed(evt);
            }
        });

        Btn28.setEnabled(false);
        Btn28.setName("Btn12"); // NOI18N
        Btn28.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn28ActionPerformed(evt);
            }
        });

        Btn29.setEnabled(false);
        Btn29.setName("Btn13"); // NOI18N
        Btn29.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn29ActionPerformed(evt);
            }
        });

        Btn30.setEnabled(false);
        Btn30.setName("Btn11"); // NOI18N
        Btn30.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn30ActionPerformed(evt);
            }
        });

        Btn31.setEnabled(false);
        Btn31.setName("Btn12"); // NOI18N
        Btn31.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn31ActionPerformed(evt);
            }
        });

        Btn32.setEnabled(false);
        Btn32.setName("Btn13"); // NOI18N
        Btn32.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn32ActionPerformed(evt);
            }
        });

        Btn33.setEnabled(false);
        Btn33.setName("Btn11"); // NOI18N
        Btn33.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn33ActionPerformed(evt);
            }
        });

        Btn34.setEnabled(false);
        Btn34.setName("Btn12"); // NOI18N
        Btn34.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn34ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row4Layout = new javax.swing.GroupLayout(row4);
        row4.setLayout(row4Layout);
        row4Layout.setHorizontalGroup(
            row4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Btn27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row4Layout.setVerticalGroup(
            row4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row4Layout.createSequentialGroup()
                .addGroup(row4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        row5.setName("row5"); // NOI18N

        Btn43.setEnabled(false);
        Btn43.setName("Btn11"); // NOI18N
        Btn43.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn43ActionPerformed(evt);
            }
        });

        Btn44.setEnabled(false);
        Btn44.setName("Btn12"); // NOI18N
        Btn44.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn44ActionPerformed(evt);
            }
        });

        Btn45.setEnabled(false);
        Btn45.setName("Btn13"); // NOI18N
        Btn45.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn45ActionPerformed(evt);
            }
        });

        Btn46.setEnabled(false);
        Btn46.setName("Btn11"); // NOI18N
        Btn46.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn46ActionPerformed(evt);
            }
        });

        Btn47.setEnabled(false);
        Btn47.setName("Btn12"); // NOI18N
        Btn47.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn47ActionPerformed(evt);
            }
        });

        Btn48.setEnabled(false);
        Btn48.setName("Btn13"); // NOI18N
        Btn48.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn48ActionPerformed(evt);
            }
        });

        Btn49.setEnabled(false);
        Btn49.setName("Btn12"); // NOI18N
        Btn49.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn49ActionPerformed(evt);
            }
        });

        Btn50.setEnabled(false);
        Btn50.setName("Btn11"); // NOI18N
        Btn50.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn50ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row5Layout = new javax.swing.GroupLayout(row5);
        row5.setLayout(row5Layout);
        row5Layout.setHorizontalGroup(
            row5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Btn43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row5Layout.setVerticalGroup(
            row5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row5Layout.createSequentialGroup()
                .addGroup(row5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn49, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        row6.setName("row6"); // NOI18N

        Btn51.setEnabled(false);
        Btn51.setName("Btn11"); // NOI18N
        Btn51.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn51ActionPerformed(evt);
            }
        });

        Btn52.setEnabled(false);
        Btn52.setName("Btn12"); // NOI18N
        Btn52.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn52ActionPerformed(evt);
            }
        });

        Btn53.setEnabled(false);
        Btn53.setName("Btn13"); // NOI18N
        Btn53.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn53ActionPerformed(evt);
            }
        });

        Btn54.setEnabled(false);
        Btn54.setName("Btn11"); // NOI18N
        Btn54.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn54ActionPerformed(evt);
            }
        });

        Btn55.setEnabled(false);
        Btn55.setName("Btn12"); // NOI18N
        Btn55.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn55ActionPerformed(evt);
            }
        });

        Btn56.setEnabled(false);
        Btn56.setName("Btn13"); // NOI18N
        Btn56.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn56ActionPerformed(evt);
            }
        });

        Btn57.setEnabled(false);
        Btn57.setName("Btn11"); // NOI18N
        Btn57.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn57ActionPerformed(evt);
            }
        });

        Btn58.setEnabled(false);
        Btn58.setName("Btn12"); // NOI18N
        Btn58.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn58ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row6Layout = new javax.swing.GroupLayout(row6);
        row6.setLayout(row6Layout);
        row6Layout.setHorizontalGroup(
            row6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Btn51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row6Layout.setVerticalGroup(
            row6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row6Layout.createSequentialGroup()
                .addGroup(row6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        row7.setName("row7"); // NOI18N

        Btn67.setEnabled(false);
        Btn67.setName("Btn11"); // NOI18N
        Btn67.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn67ActionPerformed(evt);
            }
        });

        Btn68.setEnabled(false);
        Btn68.setName("Btn12"); // NOI18N
        Btn68.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn68ActionPerformed(evt);
            }
        });

        Btn69.setEnabled(false);
        Btn69.setName("Btn13"); // NOI18N
        Btn69.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn69ActionPerformed(evt);
            }
        });

        Btn70.setEnabled(false);
        Btn70.setName("Btn11"); // NOI18N
        Btn70.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn70ActionPerformed(evt);
            }
        });

        Btn71.setEnabled(false);
        Btn71.setName("Btn12"); // NOI18N
        Btn71.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn71ActionPerformed(evt);
            }
        });

        Btn72.setEnabled(false);
        Btn72.setName("Btn13"); // NOI18N
        Btn72.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn72ActionPerformed(evt);
            }
        });

        Btn73.setEnabled(false);
        Btn73.setName("Btn12"); // NOI18N
        Btn73.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn73ActionPerformed(evt);
            }
        });

        Btn74.setEnabled(false);
        Btn74.setName("Btn11"); // NOI18N
        Btn74.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn74ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row7Layout = new javax.swing.GroupLayout(row7);
        row7.setLayout(row7Layout);
        row7Layout.setHorizontalGroup(
            row7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Btn67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn69, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn70, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row7Layout.setVerticalGroup(
            row7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row7Layout.createSequentialGroup()
                .addGroup(row7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn70, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn69, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        row8.setName("row8"); // NOI18N

        Btn59.setEnabled(false);
        Btn59.setName("Btn11"); // NOI18N
        Btn59.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn59ActionPerformed(evt);
            }
        });

        Btn60.setEnabled(false);
        Btn60.setName("Btn12"); // NOI18N
        Btn60.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn60ActionPerformed(evt);
            }
        });

        Btn61.setEnabled(false);
        Btn61.setName("Btn13"); // NOI18N
        Btn61.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn61ActionPerformed(evt);
            }
        });

        Btn62.setEnabled(false);
        Btn62.setName("Btn11"); // NOI18N
        Btn62.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn62ActionPerformed(evt);
            }
        });

        Btn63.setEnabled(false);
        Btn63.setName("Btn12"); // NOI18N
        Btn63.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn63ActionPerformed(evt);
            }
        });

        Btn64.setEnabled(false);
        Btn64.setName("Btn13"); // NOI18N
        Btn64.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn64ActionPerformed(evt);
            }
        });

        Btn65.setEnabled(false);
        Btn65.setName("Btn11"); // NOI18N
        Btn65.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn65ActionPerformed(evt);
            }
        });

        Btn66.setEnabled(false);
        Btn66.setName("Btn12"); // NOI18N
        Btn66.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn66ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout row8Layout = new javax.swing.GroupLayout(row8);
        row8.setLayout(row8Layout);
        row8Layout.setHorizontalGroup(
            row8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, row8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Btn59, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn60, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        row8Layout.setVerticalGroup(
            row8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(row8Layout.createSequentialGroup()
                .addGroup(row8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(row8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(row8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn59, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn60, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout matrixLayout = new javax.swing.GroupLayout(matrix);
        matrix.setLayout(matrixLayout);
        matrixLayout.setHorizontalGroup(
            matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, matrixLayout.createSequentialGroup()
                .addGroup(matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(row3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        matrixLayout.setVerticalGroup(
            matrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matrixLayout.createSequentialGroup()
                .addComponent(row1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(row2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(row3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(row4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(row5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(row6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(row7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(row8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        row1.getAccessibleContext().setAccessibleName("row1");
        row2.getAccessibleContext().setAccessibleName("row2");
        row3.getAccessibleContext().setAccessibleName("row3");
        row4.getAccessibleContext().setAccessibleName("row4");
        row5.getAccessibleContext().setAccessibleName("row5");
        row6.getAccessibleContext().setAccessibleName("row6");
        row7.getAccessibleContext().setAccessibleName("row7");
        row8.getAccessibleContext().setAccessibleName("row8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(matrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(matrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn11ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn11);
    }//GEN-LAST:event_Btn11ActionPerformed

    private void Btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn12ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn12);
    }//GEN-LAST:event_Btn12ActionPerformed

    private void Btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn13ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn13);
    }//GEN-LAST:event_Btn13ActionPerformed

    private void Btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn14ActionPerformed

    private void Btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn15ActionPerformed

    private void Btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn16ActionPerformed

    private void Btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn17ActionPerformed

    private void Btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn18ActionPerformed

    private void Btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn19ActionPerformed

    private void Btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn20ActionPerformed

    private void Btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn21ActionPerformed

    private void Btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn22ActionPerformed

    private void Btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn23ActionPerformed

    private void Btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn24ActionPerformed

    private void Btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn26ActionPerformed

    private void Btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn25ActionPerformed

    private void Btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn27ActionPerformed

    private void Btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn28ActionPerformed

    private void Btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn29ActionPerformed

    private void Btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn30ActionPerformed

    private void Btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn31ActionPerformed

    private void Btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn32ActionPerformed

    private void Btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn33ActionPerformed

    private void Btn34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn34ActionPerformed

    private void Btn35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn35ActionPerformed

    private void Btn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn36ActionPerformed

    private void Btn37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn37ActionPerformed

    private void Btn38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn38ActionPerformed

    private void Btn39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn39ActionPerformed

    private void Btn40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn40ActionPerformed

    private void Btn41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn41ActionPerformed

    private void Btn42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn42ActionPerformed

    private void Btn43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn43ActionPerformed

    private void Btn44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn44ActionPerformed

    private void Btn45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn45ActionPerformed

    private void Btn46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn46ActionPerformed

    private void Btn47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn47ActionPerformed

    private void Btn48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn48ActionPerformed

    private void Btn49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn49ActionPerformed

    private void Btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn50ActionPerformed

    private void Btn51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn51ActionPerformed

    private void Btn52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn52ActionPerformed

    private void Btn53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn53ActionPerformed

    private void Btn54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn54ActionPerformed

    private void Btn55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn55ActionPerformed

    private void Btn56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn56ActionPerformed

    private void Btn57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn57ActionPerformed

    private void Btn58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn58ActionPerformed

    private void Btn59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn59ActionPerformed

    private void Btn60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn60ActionPerformed

    private void Btn61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn61ActionPerformed

    private void Btn62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn62ActionPerformed

    private void Btn63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn63ActionPerformed

    private void Btn64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn64ActionPerformed

    private void Btn65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn65ActionPerformed

    private void Btn66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn66ActionPerformed

    private void Btn67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn67ActionPerformed

    private void Btn68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn68ActionPerformed

    private void Btn69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn69ActionPerformed

    private void Btn70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn70ActionPerformed

    private void Btn71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn71ActionPerformed

    private void Btn72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn72ActionPerformed

    private void Btn73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn73ActionPerformed

    private void Btn74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn74ActionPerformed
    
    void BtnActionPerformed(javax.swing.JButton btn) {
        if (btn.isEnabled() && myAgent.isTurn()) {
            btn.setBackground(Color.blue);
            deactivateButton();
            myAgent.updateBoard(btn.getName());
            notifyUser(btn.getName()+" is pressed.");
        }         
    }
    
    public void activateButton(){
        for (int i=0; i<8; i++) {
            for (int j=0; j<8;j++) {
                if (myAgent.board[i][j] == -1) {
                    getButton(i*8+j).setEnabled(true);
                }
            }
        }
    }
    
    public void deactivateButton(){
        for (int i=0; i<8; i++) {
            for (int j=0; j<8;j++) {
                getButton(i*8+j).setEnabled(false);
            }
        }
    }


    public javax.swing.JButton getButton(int btn){
        javax.swing.JButton b = mapLLToButton.get(btn);  
        return b;
    }    
    
    public void setAgent(TacAgent a) {   
        myAgent = a;   
        setTitle(myAgent.getName());   
    }   
    
    public void notifyUser(String message) {  
        System.out.println("Tic : "+message);
        //logTA.append(message+"\n");   
    } 
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TacGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TacGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TacGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TacGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TacGUIImplementation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn11;
    private javax.swing.JButton Btn12;
    private javax.swing.JButton Btn13;
    private javax.swing.JButton Btn14;
    private javax.swing.JButton Btn15;
    private javax.swing.JButton Btn16;
    private javax.swing.JButton Btn17;
    private javax.swing.JButton Btn18;
    private javax.swing.JButton Btn19;
    private javax.swing.JButton Btn20;
    private javax.swing.JButton Btn21;
    private javax.swing.JButton Btn22;
    private javax.swing.JButton Btn23;
    private javax.swing.JButton Btn24;
    private javax.swing.JButton Btn25;
    private javax.swing.JButton Btn26;
    private javax.swing.JButton Btn27;
    private javax.swing.JButton Btn28;
    private javax.swing.JButton Btn29;
    private javax.swing.JButton Btn30;
    private javax.swing.JButton Btn31;
    private javax.swing.JButton Btn32;
    private javax.swing.JButton Btn33;
    private javax.swing.JButton Btn34;
    private javax.swing.JButton Btn35;
    private javax.swing.JButton Btn36;
    private javax.swing.JButton Btn37;
    private javax.swing.JButton Btn38;
    private javax.swing.JButton Btn39;
    private javax.swing.JButton Btn40;
    private javax.swing.JButton Btn41;
    private javax.swing.JButton Btn42;
    private javax.swing.JButton Btn43;
    private javax.swing.JButton Btn44;
    private javax.swing.JButton Btn45;
    private javax.swing.JButton Btn46;
    private javax.swing.JButton Btn47;
    private javax.swing.JButton Btn48;
    private javax.swing.JButton Btn49;
    private javax.swing.JButton Btn50;
    private javax.swing.JButton Btn51;
    private javax.swing.JButton Btn52;
    private javax.swing.JButton Btn53;
    private javax.swing.JButton Btn54;
    private javax.swing.JButton Btn55;
    private javax.swing.JButton Btn56;
    private javax.swing.JButton Btn57;
    private javax.swing.JButton Btn58;
    private javax.swing.JButton Btn59;
    private javax.swing.JButton Btn60;
    private javax.swing.JButton Btn61;
    private javax.swing.JButton Btn62;
    private javax.swing.JButton Btn63;
    private javax.swing.JButton Btn64;
    private javax.swing.JButton Btn65;
    private javax.swing.JButton Btn66;
    private javax.swing.JButton Btn67;
    private javax.swing.JButton Btn68;
    private javax.swing.JButton Btn69;
    private javax.swing.JButton Btn70;
    private javax.swing.JButton Btn71;
    private javax.swing.JButton Btn72;
    private javax.swing.JButton Btn73;
    private javax.swing.JButton Btn74;
    private javax.swing.JPanel matrix;
    private javax.swing.JPanel row1;
    private javax.swing.JPanel row2;
    private javax.swing.JPanel row3;
    private javax.swing.JPanel row4;
    private javax.swing.JPanel row5;
    private javax.swing.JPanel row6;
    private javax.swing.JPanel row7;
    private javax.swing.JPanel row8;
    // End of variables declaration//GEN-END:variables
}
